table 'Cup Size'
	lineageTag: 3bf7b87c-7167-4070-9b7d-422ebfa3d68e

	column Vendor
		dataType: string
		lineageTag: 2812e0b7-78c6-4225-9089-7a2157906c7a
		summarizeBy: none
		sourceColumn: Vendor

		annotation SummarizationSetBy = Automatic

	column Size
		dataType: string
		lineageTag: 2c929b27-0e6d-4659-86ae-c3f29641fb17
		summarizeBy: none
		sourceColumn: Size

		annotation SummarizationSetBy = Automatic

	column Size_
		dataType: string
		lineageTag: 6d23ef82-852d-4c00-9d53-ee4cdeb2cbef
		summarizeBy: none
		sourceColumn: Size_

		annotation SummarizationSetBy = Automatic

	column Vendor–Size = 'Cup Size'[Vendor] & " - " & 'Cup Size'[Size]
		lineageTag: 0bc4774f-801b-409d-9ef4-f65231f26dcc
		summarizeBy: none
		sortByColumn: Sorting

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Sorting
		dataType: int64
		formatString: 0
		lineageTag: 6a2abef0-5397-4dc0-9980-23aac34a8545
		summarizeBy: none
		sourceColumn: Sorting

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	partition 'Cup Size' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Jassi\Downloads\Data\All Data for 5 vendors1.xlsx"), null, true),
				    #"Cup Size_Sheet" = Source{[Item="Cup Size",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(#"Cup Size_Sheet",{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"Vendor", type text}, {"Size", type text}, {"Size_", type text}})
				in
				    #"Changed Type1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

