name: Publish Power BI PBIP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest   # Linux runner zyada stable hai

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Install PBIP CLI
        run: dotnet tool install --global MicrosoftPowerBIPbip

      - name: Add dotnet tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Publish to Power BI
        run: |
          pbip push Coffee.pbip \
            --workspace ${{ secrets.WORKSPACE_ID }} \
            --tenant ${{ secrets.TENANT_ID }} \
            --client-id ${{ secrets.CLIENT_ID }} \
            --client-secret ${{ secrets.CLIENT_SECRET }}
