name: Publish Power BI PBIP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install pbip CLI
        run: npm install -g powerbi-pbip

      - name: Publish to Power BI
        run: |
          pbip push Coffee.pbip \
            --workspace ${{ secrets.WORKSPACE_ID }} \
            --tenant ${{ secrets.TENANT_ID }} \
            --client-id ${{ secrets.CLIENT_ID }} \
            --client-secret ${{ secrets.CLIENT_SECRET }}
