name: Publish Power BI PBIP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Publish PBIP to Power BI
        uses: microsoft/powerbi-action-pbip@v1
        with:
          workspace-id: ${{ secrets.WORKSPACE_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          pbip-path: Coffee.pbip
